/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lokaMockEcosystemSol from "./LokaMockEcosystem.sol";
export type { lokaMockEcosystemSol };
import type * as lokaVaultSol from "./LokaVault.sol";
export type { lokaVaultSol };
export type { LokaFactory } from "./LokaFactory";
