/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LokaFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "coldWallet"
      | "deployVault"
      | "getVaultAddress"
      | "idrx"
      | "router"
      | "usdc"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "VaultDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "coldWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployVault",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultAddress",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "idrx", values?: undefined): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "coldWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "idrx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace VaultDeployedEvent {
  export type InputTuple = [
    vaultAddress: AddressLike,
    owner: AddressLike,
    salt: BytesLike
  ];
  export type OutputTuple = [vaultAddress: string, owner: string, salt: string];
  export interface OutputObject {
    vaultAddress: string;
    owner: string;
    salt: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LokaFactory extends BaseContract {
  connect(runner?: ContractRunner | null): LokaFactory;
  waitForDeployment(): Promise<this>;

  interface: LokaFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  coldWallet: TypedContractMethod<[], [string], "view">;

  deployVault: TypedContractMethod<
    [_salt: BytesLike, _owner: AddressLike],
    [string],
    "nonpayable"
  >;

  getVaultAddress: TypedContractMethod<
    [_salt: BytesLike, _owner: AddressLike],
    [string],
    "view"
  >;

  idrx: TypedContractMethod<[], [string], "view">;

  router: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "coldWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deployVault"
  ): TypedContractMethod<
    [_salt: BytesLike, _owner: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getVaultAddress"
  ): TypedContractMethod<
    [_salt: BytesLike, _owner: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "idrx"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "router"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "VaultDeployed"
  ): TypedContractEvent<
    VaultDeployedEvent.InputTuple,
    VaultDeployedEvent.OutputTuple,
    VaultDeployedEvent.OutputObject
  >;

  filters: {
    "VaultDeployed(address,address,bytes32)": TypedContractEvent<
      VaultDeployedEvent.InputTuple,
      VaultDeployedEvent.OutputTuple,
      VaultDeployedEvent.OutputObject
    >;
    VaultDeployed: TypedContractEvent<
      VaultDeployedEvent.InputTuple,
      VaultDeployedEvent.OutputTuple,
      VaultDeployedEvent.OutputObject
    >;
  };
}
